//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStages.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestionStages.Properties.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Address.
        /// </summary>
        public static string Adresse {
            get {
                return ResourceManager.GetString("Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Internship site list.
        /// </summary>
        public static string ListeMilieuStage {
            get {
                return ResourceManager.GetString("ListeMilieuStage", resourceCulture);
            }
        }
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Internship site list.
        /// </summary>
        public static string ListeStage
        {
            get
            {
                return ResourceManager.GetString("ListeStage", resourceCulture);
            }
        }
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Internship site list.
        /// </summary>
        public static string AddSetStage
        {
            get
            {
                return ResourceManager.GetString("AddSetStage", resourceCulture);
            }
        }
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string Ajouter
        {
            get
            {
                return ResourceManager.GetString("Ajouter", resourceCulture);
            }
        }
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active.
        /// </summary>
        public static string Actif
        {
            get
            {
                return ResourceManager.GetString("Actif", resourceCulture);
            }
        }
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start date.
        /// </summary>
        public static string DateDeDebut
        {
            get
            {
                return ResourceManager.GetString("DateDeDebut", resourceCulture);
            }
        }
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End date.
        /// </summary>
        public static string DateDeFin
        {
            get
            {
                return ResourceManager.GetString("DateDeFin", resourceCulture);
            }
        }
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weekly work hours.
        /// </summary>
        public static string NombreDHeureParSemaine
        {
            get
            {
                return ResourceManager.GetString("NombreDHeureParSemaine", resourceCulture);
            }
        }
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Work shift.
        /// </summary>
        public static string PeriodeDeTravail
        {
            get
            {
                return ResourceManager.GetString("PeriodeDeTravail", resourceCulture);
            }
        }
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Work shift.
        /// </summary>
        public static string NombreDePostes
        {
            get
            {
                return ResourceManager.GetString("NombreDePostes", resourceCulture);
            }
        }
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back.
        /// </summary>
        public static string Retour
        {
            get
            {
                return ResourceManager.GetString("Retour", resourceCulture);
            }
        }
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string Statut
        {
            get
            {
                return ResourceManager.GetString("Statut", resourceCulture);
            }
        }
    }
}
