//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStages.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestionStages.Properties.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active.
        /// </summary>
        public static string Actif {
            get {
                return ResourceManager.GetString("Actif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Address.
        /// </summary>
        public static string Adresse {
            get {
                return ResourceManager.GetString("Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string Ajouter {
            get {
                return ResourceManager.GetString("Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add a restriction.
        /// </summary>
        public static string AjouterRestriction {
            get {
                return ResourceManager.GetString("AjouterRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add an internship site.
        /// </summary>
        public static string AjouterUnMilieuDeStage {
            get {
                return ResourceManager.GetString("AjouterUnMilieuDeStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add an intership.
        /// </summary>
        public static string AjouterUnStage {
            get {
                return ResourceManager.GetString("AjouterUnStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Annuler {
            get {
                return ResourceManager.GetString("Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à August.
        /// </summary>
        public static string Aout {
            get {
                return ResourceManager.GetString("Aout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aug.
        /// </summary>
        public static string AoutShort {
            get {
                return ResourceManager.GetString("AoutShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assign.
        /// </summary>
        public static string Assigner {
            get {
                return ResourceManager.GetString("Assigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assign internship to students.
        /// </summary>
        public static string AssignerLesStages {
            get {
                return ResourceManager.GetString("AssignerLesStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à April.
        /// </summary>
        public static string Avril {
            get {
                return ResourceManager.GetString("Avril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apr.
        /// </summary>
        public static string AvrilShort {
            get {
                return ResourceManager.GetString("AvrilShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Required field.
        /// </summary>
        public static string ChampRequis {
            get {
                return ResourceManager.GetString("ChampRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose.
        /// </summary>
        public static string Choisir {
            get {
                return ResourceManager.GetString("Choisir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Post code.
        /// </summary>
        public static string CodePostal {
            get {
                return ResourceManager.GetString("CodePostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm selection?.
        /// </summary>
        public static string ConfirmerLaSelection {
            get {
                return ResourceManager.GetString("ConfirmerLaSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coordinator.
        /// </summary>
        public static string Coordinateur {
            get {
                return ResourceManager.GetString("Coordinateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create.
        /// </summary>
        public static string Creer {
            get {
                return ResourceManager.GetString("Creer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duplicate.
        /// </summary>
        public static string CreerUneCopie {
            get {
                return ResourceManager.GetString("CreerUneCopie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start date.
        /// </summary>
        public static string DateDeDebut {
            get {
                return ResourceManager.GetString("DateDeDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End date.
        /// </summary>
        public static string DateDeFin {
            get {
                return ResourceManager.GetString("DateDeFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à December.
        /// </summary>
        public static string Decembre {
            get {
                return ResourceManager.GetString("Decembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dec.
        /// </summary>
        public static string DecembreShort {
            get {
                return ResourceManager.GetString("DecembreShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Student detail.
        /// </summary>
        public static string DetailEtudiant {
            get {
                return ResourceManager.GetString("DetailEtudiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sunday.
        /// </summary>
        public static string Dimanche {
            get {
                return ResourceManager.GetString("Dimanche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S.
        /// </summary>
        public static string DimancheAbbrev {
            get {
                return ResourceManager.GetString("DimancheAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sun.
        /// </summary>
        public static string DimancheShort {
            get {
                return ResourceManager.GetString("DimancheShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clear.
        /// </summary>
        public static string Effacer {
            get {
                return ResourceManager.GetString("Effacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sucessfully saved!.
        /// </summary>
        public static string EnregistreSucces {
            get {
                return ResourceManager.GetString("EnregistreSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string Erreur {
            get {
                return ResourceManager.GetString("Erreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Form contain one or more error.
        /// </summary>
        public static string ErreurPresenteFormulaire {
            get {
                return ResourceManager.GetString("ErreurPresenteFormulaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string Etat {
            get {
                return ResourceManager.GetString("Etat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Student.
        /// </summary>
        public static string Etudiant {
            get {
                return ResourceManager.GetString("Etudiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not assign student.
        /// </summary>
        public static string EtudiantNonAssigner {
            get {
                return ResourceManager.GetString("EtudiantNonAssigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à February.
        /// </summary>
        public static string Fevrier {
            get {
                return ResourceManager.GetString("Fevrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Feb.
        /// </summary>
        public static string FevrierShort {
            get {
                return ResourceManager.GetString("FevrierShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search criteria.
        /// </summary>
        public static string FiltreDeRecherche {
            get {
                return ResourceManager.GetString("FiltreDeRecherche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use a valid format..
        /// </summary>
        public static string FormatValide {
            get {
                return ResourceManager.GetString("FormatValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print.
        /// </summary>
        public static string Imprimer {
            get {
                return ResourceManager.GetString("Imprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Inactive.
        /// </summary>
        public static string Inactif {
            get {
                return ResourceManager.GetString("Inactif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à January.
        /// </summary>
        public static string Janvier {
            get {
                return ResourceManager.GetString("Janvier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jan.
        /// </summary>
        public static string JanvierShort {
            get {
                return ResourceManager.GetString("JanvierShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thursday.
        /// </summary>
        public static string Jeudi {
            get {
                return ResourceManager.GetString("Jeudi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à T.
        /// </summary>
        public static string JeudiAbbrev {
            get {
                return ResourceManager.GetString("JeudiAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thu.
        /// </summary>
        public static string JeudiShort {
            get {
                return ResourceManager.GetString("JeudiShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Day.
        /// </summary>
        public static string Jour {
            get {
                return ResourceManager.GetString("Jour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à July.
        /// </summary>
        public static string Juillet {
            get {
                return ResourceManager.GetString("Juillet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jul.
        /// </summary>
        public static string JuilletShort {
            get {
                return ResourceManager.GetString("JuilletShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à June.
        /// </summary>
        public static string Juin {
            get {
                return ResourceManager.GetString("Juin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jun.
        /// </summary>
        public static string JuinShort {
            get {
                return ResourceManager.GetString("JuinShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Internship site list.
        /// </summary>
        public static string ListeMilieuStage {
            get {
                return ResourceManager.GetString("ListeMilieuStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Restrictions list.
        /// </summary>
        public static string ListeRestriction {
            get {
                return ResourceManager.GetString("ListeRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Internship list.
        /// </summary>
        public static string ListeStage {
            get {
                return ResourceManager.GetString("ListeStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Monday.
        /// </summary>
        public static string Lundi {
            get {
                return ResourceManager.GetString("Lundi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M.
        /// </summary>
        public static string LundiAbbrev {
            get {
                return ResourceManager.GetString("LundiAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mon.
        /// </summary>
        public static string LundiShort {
            get {
                return ResourceManager.GetString("LundiShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à May.
        /// </summary>
        public static string Mai {
            get {
                return ResourceManager.GetString("Mai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à May.
        /// </summary>
        public static string MaiShort {
            get {
                return ResourceManager.GetString("MaiShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tuesday.
        /// </summary>
        public static string Mardi {
            get {
                return ResourceManager.GetString("Mardi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à T.
        /// </summary>
        public static string MardiAbbrev {
            get {
                return ResourceManager.GetString("MardiAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tue.
        /// </summary>
        public static string MardiShort {
            get {
                return ResourceManager.GetString("MardiShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à March.
        /// </summary>
        public static string Mars {
            get {
                return ResourceManager.GetString("Mars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mar.
        /// </summary>
        public static string MarsShort {
            get {
                return ResourceManager.GetString("MarsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wednesday.
        /// </summary>
        public static string Mercredi {
            get {
                return ResourceManager.GetString("Mercredi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W.
        /// </summary>
        public static string MercrediAbbrev {
            get {
                return ResourceManager.GetString("MercrediAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wed.
        /// </summary>
        public static string MercrediShort {
            get {
                return ResourceManager.GetString("MercrediShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intership site.
        /// </summary>
        public static string MilieuDeStage {
            get {
                return ResourceManager.GetString("MilieuDeStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Available Internship site .
        /// </summary>
        public static string MilieuDeStagesDisponibles {
            get {
                return ResourceManager.GetString("MilieuDeStagesDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modify a restriction.
        /// </summary>
        public static string ModifierRestriction {
            get {
                return ResourceManager.GetString("ModifierRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update an internship site.
        /// </summary>
        public static string ModifierUnMilieuDeStage {
            get {
                return ResourceManager.GetString("ModifierUnMilieuDeStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update an internship.
        /// </summary>
        public static string ModifierUnStage {
            get {
                return ResourceManager.GetString("ModifierUnStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last name.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Available workstation.
        /// </summary>
        public static string NombreDePostes {
            get {
                return ResourceManager.GetString("NombreDePostes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Not enought intership selected.
        /// </summary>
        public static string NombreDeStagesSelectionnesInsufisant {
            get {
                return ResourceManager.GetString("NombreDeStagesSelectionnesInsufisant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Weekly work hours.
        /// </summary>
        public static string NombreDHeureParSemaine {
            get {
                return ResourceManager.GetString("NombreDHeureParSemaine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum weekly work hours.
        /// </summary>
        public static string NombreMaximumDHeureSemaine {
            get {
                return ResourceManager.GetString("NombreMaximumDHeureSemaine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimal weekly work hours.
        /// </summary>
        public static string NombreMinimumDHeureSemaine {
            get {
                return ResourceManager.GetString("NombreMinimumDHeureSemaine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string Non {
            get {
                return ResourceManager.GetString("Non", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à November.
        /// </summary>
        public static string Novembre {
            get {
                return ResourceManager.GetString("Novembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nov.
        /// </summary>
        public static string NovembreShort {
            get {
                return ResourceManager.GetString("NovembreShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Night.
        /// </summary>
        public static string Nuit {
            get {
                return ResourceManager.GetString("Nuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choice#.
        /// </summary>
        public static string NumeroChoix {
            get {
                return ResourceManager.GetString("NumeroChoix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Civic number.
        /// </summary>
        public static string NumeroCivique {
            get {
                return ResourceManager.GetString("NumeroCivique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone number.
        /// </summary>
        public static string NumeroDeTelephone {
            get {
                return ResourceManager.GetString("NumeroDeTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à October.
        /// </summary>
        public static string Octobre {
            get {
                return ResourceManager.GetString("Octobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oct.
        /// </summary>
        public static string OctobreShort {
            get {
                return ResourceManager.GetString("OctobreShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string Oui {
            get {
                return ResourceManager.GetString("Oui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Country.
        /// </summary>
        public static string Pays {
            get {
                return ResourceManager.GetString("Pays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Work shift.
        /// </summary>
        public static string PeriodeDeTravail {
            get {
                return ResourceManager.GetString("PeriodeDeTravail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Workstation.
        /// </summary>
        public static string Postes {
            get {
                return ResourceManager.GetString("Postes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First name.
        /// </summary>
        public static string Prenom {
            get {
                return ResourceManager.GetString("Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        public static string Rechercher {
            get {
                return ResourceManager.GetString("Rechercher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back.
        /// </summary>
        public static string Retour {
            get {
                return ResourceManager.GetString("Retour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Road.
        /// </summary>
        public static string Rue {
            get {
                return ResourceManager.GetString("Rue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saturday.
        /// </summary>
        public static string Samedi {
            get {
                return ResourceManager.GetString("Samedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S.
        /// </summary>
        public static string SamediAbbrev {
            get {
                return ResourceManager.GetString("SamediAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sat.
        /// </summary>
        public static string SamediShort {
            get {
                return ResourceManager.GetString("SamediShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string Sauvegarder {
            get {
                return ResourceManager.GetString("Sauvegarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à September.
        /// </summary>
        public static string Septembre {
            get {
                return ResourceManager.GetString("Septembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sep.
        /// </summary>
        public static string SeptembreShort {
            get {
                return ResourceManager.GetString("SeptembreShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Evening.
        /// </summary>
        public static string Soiree {
            get {
                return ResourceManager.GetString("Soiree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Internship waiting to be assign.
        /// </summary>
        public static string StageEnAttenteAssignation {
            get {
                return ResourceManager.GetString("StageEnAttenteAssignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Intership available at this site.
        /// </summary>
        public static string StagesDisponiblesDansCeMilieu {
            get {
                return ResourceManager.GetString("StagesDisponiblesDansCeMilieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string Statut {
            get {
                return ResourceManager.GetString("Statut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supervisor.
        /// </summary>
        public static string Superviseur {
            get {
                return ResourceManager.GetString("Superviseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Part-time.
        /// </summary>
        public static string TempsPartiel {
            get {
                return ResourceManager.GetString("TempsPartiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Full-Time.
        /// </summary>
        public static string TempsPleins {
            get {
                return ResourceManager.GetString("TempsPleins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Title.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Friday.
        /// </summary>
        public static string Vendredi {
            get {
                return ResourceManager.GetString("Vendredi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à F.
        /// </summary>
        public static string VendrediAbbrev {
            get {
                return ResourceManager.GetString("VendrediAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fri.
        /// </summary>
        public static string VendrediShort {
            get {
                return ResourceManager.GetString("VendrediShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please confirm selection.
        /// </summary>
        public static string VeuillezConfirmerLaSelection {
            get {
                return ResourceManager.GetString("VeuillezConfirmerLaSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à City.
        /// </summary>
        public static string Ville {
            get {
                return ResourceManager.GetString("Ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View an internship site.
        /// </summary>
        public static string VisionnerUnMilieuDeStage {
            get {
                return ResourceManager.GetString("VisionnerUnMilieuDeStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View an internship.
        /// </summary>
        public static string VisionnerUnStage {
            get {
                return ResourceManager.GetString("VisionnerUnStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à See.
        /// </summary>
        public static string Voir {
            get {
                return ResourceManager.GetString("Voir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
