//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionStages.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GestionStages.Properties.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Actif {
            get {
                return ResourceManager.GetString("Actif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Adresse {
            get {
                return ResourceManager.GetString("Adresse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Ajouter {
            get {
                return ResourceManager.GetString("Ajouter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a restriction.
        /// </summary>
        public static string AjouterRestriction {
            get {
                return ResourceManager.GetString("AjouterRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an internship site.
        /// </summary>
        public static string AjouterUnMilieuDeStage {
            get {
                return ResourceManager.GetString("AjouterUnMilieuDeStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an intership.
        /// </summary>
        public static string AjouterUnStage {
            get {
                return ResourceManager.GetString("AjouterUnStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Annuler {
            get {
                return ResourceManager.GetString("Annuler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August.
        /// </summary>
        public static string Aout {
            get {
                return ResourceManager.GetString("Aout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug.
        /// </summary>
        public static string AoutShort {
            get {
                return ResourceManager.GetString("AoutShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string Assigner {
            get {
                return ResourceManager.GetString("Assigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign internship to students.
        /// </summary>
        public static string AssignerLesStages {
            get {
                return ResourceManager.GetString("AssignerLesStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        public static string Avril {
            get {
                return ResourceManager.GetString("Avril", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apr.
        /// </summary>
        public static string AvrilShort {
            get {
                return ResourceManager.GetString("AvrilShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string ChampRequis {
            get {
                return ResourceManager.GetString("ChampRequis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choisir {
            get {
                return ResourceManager.GetString("Choisir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post code.
        /// </summary>
        public static string CodePostal {
            get {
                return ResourceManager.GetString("CodePostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm selection?.
        /// </summary>
        public static string ConfirmerLaSelection {
            get {
                return ResourceManager.GetString("ConfirmerLaSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinator.
        /// </summary>
        public static string Coordinateur {
            get {
                return ResourceManager.GetString("Coordinateur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Courriel {
            get {
                return ResourceManager.GetString("Courriel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Creer {
            get {
                return ResourceManager.GetString("Creer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string CreerUneCopie {
            get {
                return ResourceManager.GetString("CreerUneCopie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DA.
        /// </summary>
        public static string DA {
            get {
                return ResourceManager.GetString("DA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        public static string DateDeDebut {
            get {
                return ResourceManager.GetString("DateDeDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string DateDeFin {
            get {
                return ResourceManager.GetString("DateDeFin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        public static string Decembre {
            get {
                return ResourceManager.GetString("Decembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec.
        /// </summary>
        public static string DecembreShort {
            get {
                return ResourceManager.GetString("DecembreShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string DetailEtudiant {
            get {
                return ResourceManager.GetString("DetailEtudiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Dimanche {
            get {
                return ResourceManager.GetString("Dimanche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string DimancheAbbrev {
            get {
                return ResourceManager.GetString("DimancheAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        public static string DimancheShort {
            get {
                return ResourceManager.GetString("DimancheShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Effacer {
            get {
                return ResourceManager.GetString("Effacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessfully saved!.
        /// </summary>
        public static string EnregistreSucces {
            get {
                return ResourceManager.GetString("EnregistreSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Erreur {
            get {
                return ResourceManager.GetString("Erreur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while retreiving the current student.
        /// </summary>
        public static string ErreurChargementEtudiant {
            get {
                return ResourceManager.GetString("ErreurChargementEtudiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form contain one or more error.
        /// </summary>
        public static string ErreurPresenteFormulaire {
            get {
                return ResourceManager.GetString("ErreurPresenteFormulaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must give a supervisor.
        /// </summary>
        public static string ErreurSuperviseur {
            get {
                return ResourceManager.GetString("ErreurSuperviseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Etat {
            get {
                return ResourceManager.GetString("Etat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Etudiant {
            get {
                return ResourceManager.GetString("Etudiant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The student already made a choice for this internship.
        /// </summary>
        public static string EtudiantDejaDansLesChoixStages {
            get {
                return ResourceManager.GetString("EtudiantDejaDansLesChoixStages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not assign student.
        /// </summary>
        public static string EtudiantNonAssigner {
            get {
                return ResourceManager.GetString("EtudiantNonAssigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining students.
        /// </summary>
        public static string EtudiantsRestants {
            get {
                return ResourceManager.GetString("EtudiantsRestants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to February.
        /// </summary>
        public static string Fevrier {
            get {
                return ResourceManager.GetString("Fevrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb.
        /// </summary>
        public static string FevrierShort {
            get {
                return ResourceManager.GetString("FevrierShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search criteria.
        /// </summary>
        public static string FiltreDeRecherche {
            get {
                return ResourceManager.GetString("FiltreDeRecherche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use a valid format..
        /// </summary>
        public static string FormatValide {
            get {
                return ResourceManager.GetString("FormatValide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number without decimal. .
        /// </summary>
        public static string FormatValideChiffre {
            get {
                return ResourceManager.GetString("FormatValideChiffre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid number with a maximum of 2 decimal..
        /// </summary>
        public static string FormatValideDecimale {
            get {
                return ResourceManager.GetString("FormatValideDecimale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Imprimer {
            get {
                return ResourceManager.GetString("Imprimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        public static string Inactif {
            get {
                return ResourceManager.GetString("Inactif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to January.
        /// </summary>
        public static string Janvier {
            get {
                return ResourceManager.GetString("Janvier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan.
        /// </summary>
        public static string JanvierShort {
            get {
                return ResourceManager.GetString("JanvierShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Jeudi {
            get {
                return ResourceManager.GetString("Jeudi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string JeudiAbbrev {
            get {
                return ResourceManager.GetString("JeudiAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        public static string JeudiShort {
            get {
                return ResourceManager.GetString("JeudiShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Jour {
            get {
                return ResourceManager.GetString("Jour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to July.
        /// </summary>
        public static string Juillet {
            get {
                return ResourceManager.GetString("Juillet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jul.
        /// </summary>
        public static string JuilletShort {
            get {
                return ResourceManager.GetString("JuilletShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to June.
        /// </summary>
        public static string Juin {
            get {
                return ResourceManager.GetString("Juin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun.
        /// </summary>
        public static string JuinShort {
            get {
                return ResourceManager.GetString("JuinShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internship site list.
        /// </summary>
        public static string ListeMilieuStage {
            get {
                return ResourceManager.GetString("ListeMilieuStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrictions list.
        /// </summary>
        public static string ListeRestriction {
            get {
                return ResourceManager.GetString("ListeRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrictions list from the internship site.
        /// </summary>
        public static string ListesDesRestrictionsDuMilieuDeStage {
            get {
                return ResourceManager.GetString("ListesDesRestrictionsDuMilieuDeStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internship list.
        /// </summary>
        public static string ListeStage {
            get {
                return ResourceManager.GetString("ListeStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Lundi {
            get {
                return ResourceManager.GetString("Lundi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string LundiAbbrev {
            get {
                return ResourceManager.GetString("LundiAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        public static string LundiShort {
            get {
                return ResourceManager.GetString("LundiShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string Mai {
            get {
                return ResourceManager.GetString("Mai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May.
        /// </summary>
        public static string MaiShort {
            get {
                return ResourceManager.GetString("MaiShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Mardi {
            get {
                return ResourceManager.GetString("Mardi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        public static string MardiAbbrev {
            get {
                return ResourceManager.GetString("MardiAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        public static string MardiShort {
            get {
                return ResourceManager.GetString("MardiShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to March.
        /// </summary>
        public static string Mars {
            get {
                return ResourceManager.GetString("Mars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mar.
        /// </summary>
        public static string MarsShort {
            get {
                return ResourceManager.GetString("MarsShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Mercredi {
            get {
                return ResourceManager.GetString("Mercredi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W.
        /// </summary>
        public static string MercrediAbbrev {
            get {
                return ResourceManager.GetString("MercrediAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        public static string MercrediShort {
            get {
                return ResourceManager.GetString("MercrediShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intership site.
        /// </summary>
        public static string MilieuDeStage {
            get {
                return ResourceManager.GetString("MilieuDeStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Internship site .
        /// </summary>
        public static string MilieuDeStagesDisponibles {
            get {
                return ResourceManager.GetString("MilieuDeStagesDisponibles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Modifier {
            get {
                return ResourceManager.GetString("Modifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify a restriction.
        /// </summary>
        public static string ModifierRestriction {
            get {
                return ResourceManager.GetString("ModifierRestriction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update an internship site.
        /// </summary>
        public static string ModifierUnMilieuDeStage {
            get {
                return ResourceManager.GetString("ModifierUnMilieuDeStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update an internship.
        /// </summary>
        public static string ModifierUnStage {
            get {
                return ResourceManager.GetString("ModifierUnStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No email address .
        /// </summary>
        public static string NoEmail {
            get {
                return ResourceManager.GetString("NoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Nom {
            get {
                return ResourceManager.GetString("Nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available workstation.
        /// </summary>
        public static string NombreDePostes {
            get {
                return ResourceManager.GetString("NombreDePostes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enought intership selected.
        /// </summary>
        public static string NombreDeStagesSelectionnesInsufisant {
            get {
                return ResourceManager.GetString("NombreDeStagesSelectionnesInsufisant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly work hours.
        /// </summary>
        public static string NombreDHeureParSemaine {
            get {
                return ResourceManager.GetString("NombreDHeureParSemaine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum weekly work hours.
        /// </summary>
        public static string NombreMaximumDHeureSemaine {
            get {
                return ResourceManager.GetString("NombreMaximumDHeureSemaine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimal weekly work hours.
        /// </summary>
        public static string NombreMinimumDHeureSemaine {
            get {
                return ResourceManager.GetString("NombreMinimumDHeureSemaine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Non {
            get {
                return ResourceManager.GetString("Non", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        public static string Novembre {
            get {
                return ResourceManager.GetString("Novembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov.
        /// </summary>
        public static string NovembreShort {
            get {
                return ResourceManager.GetString("NovembreShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        public static string Nuit {
            get {
                return ResourceManager.GetString("Nuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choice#.
        /// </summary>
        public static string NumeroChoix {
            get {
                return ResourceManager.GetString("NumeroChoix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civic number.
        /// </summary>
        public static string NumeroCivique {
            get {
                return ResourceManager.GetString("NumeroCivique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string NumeroDeTelephone {
            get {
                return ResourceManager.GetString("NumeroDeTelephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to October.
        /// </summary>
        public static string Octobre {
            get {
                return ResourceManager.GetString("Octobre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oct.
        /// </summary>
        public static string OctobreShort {
            get {
                return ResourceManager.GetString("OctobreShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Oui {
            get {
                return ResourceManager.GetString("Oui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Pays {
            get {
                return ResourceManager.GetString("Pays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work shift.
        /// </summary>
        public static string PeriodeDeTravail {
            get {
                return ResourceManager.GetString("PeriodeDeTravail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workstation.
        /// </summary>
        public static string Postes {
            get {
                return ResourceManager.GetString("Postes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Prenom {
            get {
                return ResourceManager.GetString("Prenom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course of study.
        /// </summary>
        public static string Programme {
            get {
                return ResourceManager.GetString("Programme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Rechercher {
            get {
                return ResourceManager.GetString("Rechercher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available restriction.
        /// </summary>
        public static string RestrictionDisponnible {
            get {
                return ResourceManager.GetString("RestrictionDisponnible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrictions.
        /// </summary>
        public static string Restrictions {
            get {
                return ResourceManager.GetString("Restrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled restrictions.
        /// </summary>
        public static string RestrictionsActives {
            get {
                return ResourceManager.GetString("RestrictionsActives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Retour {
            get {
                return ResourceManager.GetString("Retour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road.
        /// </summary>
        public static string Rue {
            get {
                return ResourceManager.GetString("Rue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Samedi {
            get {
                return ResourceManager.GetString("Samedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S.
        /// </summary>
        public static string SamediAbbrev {
            get {
                return ResourceManager.GetString("SamediAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        public static string SamediShort {
            get {
                return ResourceManager.GetString("SamediShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Sauvegarder {
            get {
                return ResourceManager.GetString("Sauvegarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        public static string Septembre {
            get {
                return ResourceManager.GetString("Septembre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sep.
        /// </summary>
        public static string SeptembreShort {
            get {
                return ResourceManager.GetString("SeptembreShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evening.
        /// </summary>
        public static string Soiree {
            get {
                return ResourceManager.GetString("Soiree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internship waiting to be assign.
        /// </summary>
        public static string StageEnAttenteAssignation {
            get {
                return ResourceManager.GetString("StageEnAttenteAssignation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intership available at this site.
        /// </summary>
        public static string StagesDisponiblesDansCeMilieu {
            get {
                return ResourceManager.GetString("StagesDisponiblesDansCeMilieu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Statut {
            get {
                return ResourceManager.GetString("Statut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor.
        /// </summary>
        public static string Superviseur {
            get {
                return ResourceManager.GetString("Superviseur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part-time.
        /// </summary>
        public static string TempsPartiel {
            get {
                return ResourceManager.GetString("TempsPartiel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full-Time.
        /// </summary>
        public static string TempsPleins {
            get {
                return ResourceManager.GetString("TempsPleins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Titre {
            get {
                return ResourceManager.GetString("Titre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Vendredi {
            get {
                return ResourceManager.GetString("Vendredi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string VendrediAbbrev {
            get {
                return ResourceManager.GetString("VendrediAbbrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        public static string VendrediShort {
            get {
                return ResourceManager.GetString("VendrediShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm selection.
        /// </summary>
        public static string VeuillezConfirmerLaSelection {
            get {
                return ResourceManager.GetString("VeuillezConfirmerLaSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Ville {
            get {
                return ResourceManager.GetString("Ville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View an internship site.
        /// </summary>
        public static string VisionnerUnMilieuDeStage {
            get {
                return ResourceManager.GetString("VisionnerUnMilieuDeStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View an internship.
        /// </summary>
        public static string VisionnerUnStage {
            get {
                return ResourceManager.GetString("VisionnerUnStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See.
        /// </summary>
        public static string Voir {
            get {
                return ResourceManager.GetString("Voir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
